-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_udp_core_ctrl_mmap_ipb is

  constant IPBUS_SEL_WIDTH: positive := 3;
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_udp_core_ctrl_mmap_ipb(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically generated VHDL (Tue Apr  4 14:55:26 2023)
  constant N_SLV_NZ_RST_CTRL: integer := 0;
  constant N_SLV_RX_PACKET_COUNTERS: integer := 1;
  constant N_SLV_TX_PACKET_COUNTERS: integer := 2;
  constant N_SLV_ID_STAT: integer := 3;
  constant N_SLAVES: integer := 4;
-- END automatically generated VHDL

    
end ipbus_decode_udp_core_ctrl_mmap_ipb;

package body ipbus_decode_udp_core_ctrl_mmap_ipb is

  function ipbus_sel_udp_core_ctrl_mmap_ipb(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically generated VHDL (Tue Apr  4 14:55:26 2023)
    if    std_match(addr, "--------------------------00----") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_NZ_RST_CTRL, IPBUS_SEL_WIDTH)); -- nz_rst_ctrl / base 0x00000000 / mask 0x00000030
    elsif std_match(addr, "--------------------------01----") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_RX_PACKET_COUNTERS, IPBUS_SEL_WIDTH)); -- rx_packet_counters / base 0x00000010 / mask 0x00000030
    elsif std_match(addr, "--------------------------10----") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_TX_PACKET_COUNTERS, IPBUS_SEL_WIDTH)); -- tx_packet_counters / base 0x00000020 / mask 0x00000030
    elsif std_match(addr, "--------------------------11----") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_ID_STAT, IPBUS_SEL_WIDTH)); -- id_stat / base 0x00000030 / mask 0x00000030
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_udp_core_ctrl_mmap_ipb;

end ipbus_decode_udp_core_ctrl_mmap_ipb;

