`include "PACKAGE.types.colData.sv"
`include "PACKAGE.constants.colData.sv"

module VDDCells ( inout    logic  VDD_IO,
                  inout    logic  VDD_LARASIC,
                  inout    logic  VDD_CORE
                );

// TOP (LEFT to RIGHT)
PVDD3A VDDIOTOPINST1 ();
PVDD3A VDDIOTOPINST2 ();
PVDD3AC VDDCOREINST3 ();
PVDD3AC VDDCOREINST4 ();
PVDD3A VDDIOTOPINST5 ();
PVDD3A VDDIOTOPINST6 ();
PVDD3A VDDIOTOPINST7 ();
PVDD3A VDDIOTOPINST8 ();

// LEFT (TOP to BOTTOM)
PVDD3A VDDIOLEFTINST1 ();
PVDD3A VDDIOLEFTINST2 ();
PVDD3AC VDDCORELEFTINST3 ();
PVDD3A VDDIOLEFTINST4 ();
PVDD3A VDDIOLEFTINST5 ();
PVDD3A VDDIOLEFTINST6 ();
PVDD3A VDDIOLEFTINST7 ();

// BOTTOM (LEFT to RIGHT)
PVDD3AC VDDCOREBOTTOMINST1 ();
PVDD3AC VDDCOREBOTTOMINST2 ();
PVDD3A VDDIOBOTTOMINST3 ();
PVDD3A VDDIOBOTTOMINST4 ();
PVDD3A VDDIOBOTTOMINST5 ();
PVDD3A VDDIOBOTTOMINST6 ();
PVDD3AC VDDCOREBOTTOMINST7 ();
PVDD3AC VDDCOREBOTTOMINST8 ();

// RIGHT (TOP to BOTTOM)
PVDD3AC VDDCORERIGHTINST1 ();
PVDD3AC VDDCORERIGHTINST2 ();
PVDD3A VDDIORIGHTINST3 ();
PVDD3A VDDIORIGHTINST4 ();
PVDD3A VDDLARASICRIGHTINST5 ();
PVDD3A VDDLARASICRIGHTINST6 ();

endmodule
