# Program PL CLK1 to 10MHz manually
# Normally PL clocks are programmed by FSBL,
# but Petalinux 2020.1 generates invalid FSBL.
# So we're using FSBL generated by Petalinux 2019
# from skeleton design without PL CLK1
devmem 0xff5e00c4 32 0x1033200

