-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_tx_mux_wib is

  constant IPBUS_SEL_WIDTH: positive := 3;
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_tx_mux_wib(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically generated VHDL (Mon Mar 20 20:40:10 2023)
  constant N_SLV_INFO: integer := 0;
  constant N_SLV_CSR: integer := 1;
  constant N_SLV_SAMP: integer := 2;
  constant N_SLV_MUX: integer := 3;
  constant N_SLV_UDP: integer := 4;
  constant N_SLAVES: integer := 5;
-- END automatically generated VHDL

    
end ipbus_decode_tx_mux_wib;

package body ipbus_decode_tx_mux_wib is

  function ipbus_sel_tx_mux_wib(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically generated VHDL (Mon Mar 20 20:40:10 2023)
    if    std_match(addr, "----------------------0--0--00--") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_INFO, IPBUS_SEL_WIDTH)); -- info / base 0x00000000 / mask 0x0000024c
    elsif std_match(addr, "----------------------0--0--01--") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CSR, IPBUS_SEL_WIDTH)); -- csr / base 0x00000004 / mask 0x0000024c
    elsif std_match(addr, "----------------------0--0--10--") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_SAMP, IPBUS_SEL_WIDTH)); -- samp / base 0x00000008 / mask 0x0000024c
    elsif std_match(addr, "----------------------0--1------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_MUX, IPBUS_SEL_WIDTH)); -- mux / base 0x00000040 / mask 0x00000240
    elsif std_match(addr, "----------------------1---------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_UDP, IPBUS_SEL_WIDTH)); -- udp / base 0x00000200 / mask 0x00000200
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_tx_mux_wib;

end ipbus_decode_tx_mux_wib;

