`timescale 1ns / 1ps

module coldata_rx_tux
(
    input wire [0 : 0] gtwiz_userclk_tx_reset_in         ,
    output wire [0 : 0] gtwiz_userclk_tx_srcclk_out      ,
    output wire [0 : 0] gtwiz_userclk_tx_usrclk_out      ,
    output wire [0 : 0] gtwiz_userclk_tx_usrclk2_out     ,
    output wire [0 : 0] gtwiz_userclk_tx_active_out      ,
    input wire [0 : 0] gtwiz_userclk_rx_reset_in         ,
    output wire [0 : 0] gtwiz_userclk_rx_srcclk_out      ,
    output wire [0 : 0] gtwiz_userclk_rx_usrclk_out      ,
    output wire [0 : 0] gtwiz_userclk_rx_usrclk2_out     ,
    output wire [0 : 0] gtwiz_userclk_rx_active_out      ,
    input wire [0 : 0] gtwiz_reset_clk_freerun_in        ,
    input wire [0 : 0] gtwiz_reset_all_in                ,
    input wire [0 : 0] gtwiz_reset_tx_pll_and_datapath_in,
    input wire [0 : 0] gtwiz_reset_tx_datapath_in        ,
    input wire [0 : 0] gtwiz_reset_rx_pll_and_datapath_in,
    input wire [0 : 0] gtwiz_reset_rx_datapath_in        ,
    output wire [0 : 0] gtwiz_reset_rx_cdr_stable_out    ,
    output wire [0 : 0] gtwiz_reset_tx_done_out          ,
    output wire [0 : 0] gtwiz_reset_rx_done_out          ,
    input wire [255 : 0] gtwiz_userdata_tx_in            ,
    output wire [255 : 0] gtwiz_userdata_rx_out          ,
    input wire [3 : 0] gtrefclk00_in                     ,
    output wire [3 : 0] qpll0outclk_out                  ,
    output wire [3 : 0] qpll0outrefclk_out               ,
    input wire [15 : 0] gthrxn_in                        ,
    input wire [15 : 0] gthrxp_in                        ,
    input wire [15 : 0] rx8b10ben_in                     ,
    input wire [15 : 0] rxcommadeten_in                  ,
    input wire [15 : 0] rxmcommaalignen_in               ,
    input wire [15 : 0] rxpcommaalignen_in               ,
    input wire [15 : 0] tx8b10ben_in                     ,
    input wire [255 : 0] txctrl0_in                      ,
    input wire [255 : 0] txctrl1_in                      ,
    input wire [127 : 0] txctrl2_in                      ,
    input wire [31 : 0] txpd_in                          ,
    output wire [15 : 0] gthtxn_out                      ,
    output wire [15 : 0] gthtxp_out                      ,
    output wire [15 : 0] gtpowergood_out                 ,
    output wire [15 : 0] rxbyteisaligned_out             ,
    output wire [15 : 0] rxbyterealign_out               ,
    output wire [15 : 0] rxcommadet_out                  ,
    output wire [255 : 0] rxctrl0_out                    ,
    output wire [255 : 0] rxctrl1_out                    ,
    output wire [127 : 0] rxctrl2_out                    ,
    output wire [127 : 0] rxctrl3_out                    ,
    output wire [15 : 0] rxpmaresetdone_out              ,
    output wire [15 : 0] txpmaresetdone_out              
);

coldata_rx crx 
(
  .gtwiz_userclk_tx_reset_in(gtwiz_userclk_tx_reset_in),                    
  .gtwiz_userclk_tx_srcclk_out(gtwiz_userclk_tx_srcclk_out),                
  .gtwiz_userclk_tx_usrclk_out(gtwiz_userclk_tx_usrclk_out),                
  .gtwiz_userclk_tx_usrclk2_out(gtwiz_userclk_tx_usrclk2_out),              
  .gtwiz_userclk_tx_active_out(gtwiz_userclk_tx_active_out),                
  .gtwiz_userclk_rx_reset_in(gtwiz_userclk_rx_reset_in),                    
  .gtwiz_userclk_rx_srcclk_out(gtwiz_userclk_rx_srcclk_out),                
  .gtwiz_userclk_rx_usrclk_out(gtwiz_userclk_rx_usrclk_out),                
  .gtwiz_userclk_rx_usrclk2_out(gtwiz_userclk_rx_usrclk2_out),              
  .gtwiz_userclk_rx_active_out(gtwiz_userclk_rx_active_out),                
  .gtwiz_reset_clk_freerun_in(gtwiz_reset_clk_freerun_in),                  
  .gtwiz_reset_all_in(gtwiz_reset_all_in),                                  
  .gtwiz_reset_tx_pll_and_datapath_in(gtwiz_reset_tx_pll_and_datapath_in),  
  .gtwiz_reset_tx_datapath_in(gtwiz_reset_tx_datapath_in),                  
  .gtwiz_reset_rx_pll_and_datapath_in(gtwiz_reset_rx_pll_and_datapath_in),  
  .gtwiz_reset_rx_datapath_in(gtwiz_reset_rx_datapath_in),                  
  .gtwiz_reset_rx_cdr_stable_out(gtwiz_reset_rx_cdr_stable_out),            
  .gtwiz_reset_tx_done_out(gtwiz_reset_tx_done_out),                        
  .gtwiz_reset_rx_done_out(gtwiz_reset_rx_done_out),                        
  .gtwiz_userdata_tx_in(gtwiz_userdata_tx_in),                              
  .gtwiz_userdata_rx_out(gtwiz_userdata_rx_out),                            
  .gtrefclk00_in(gtrefclk00_in),                                            
  .qpll0outclk_out(qpll0outclk_out),                                        
  .qpll0outrefclk_out(qpll0outrefclk_out),                                  
  .gthrxn_in(gthrxn_in),                                                    
  .gthrxp_in(gthrxp_in),                                                    
  .rx8b10ben_in(rx8b10ben_in),                                              
  .rxcommadeten_in(rxcommadeten_in),                                        
  .rxmcommaalignen_in(rxmcommaalignen_in),                                  
  .rxpcommaalignen_in(rxpcommaalignen_in),                                  
  .tx8b10ben_in(tx8b10ben_in),                                              
  .txctrl0_in(txctrl0_in),                                                  
  .txctrl1_in(txctrl1_in),                                                  
  .txctrl2_in(txctrl2_in),                                                  
  .txpd_in(txpd_in),                                                        
  .gthtxn_out(gthtxn_out),                                                  
  .gthtxp_out(gthtxp_out),                                                  
  .gtpowergood_out(gtpowergood_out),                                        
  .rxbyteisaligned_out(rxbyteisaligned_out),                                
  .rxbyterealign_out(rxbyterealign_out),                                    
  .rxcommadet_out(rxcommadet_out),                                          
  .rxctrl0_out(rxctrl0_out),                                                
  .rxctrl1_out(rxctrl1_out),                                                
  .rxctrl2_out(rxctrl2_out),                                                
  .rxctrl3_out(rxctrl3_out),                                                
  .rxpmaresetdone_out(rxpmaresetdone_out),                                  
  .txpmaresetdone_out(txpmaresetdone_out)                                   
);


endmodule
