-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_arp_mode_ctrl_mmap_ipb is

  constant IPBUS_SEL_WIDTH: positive := 3;
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_arp_mode_ctrl_mmap_ipb(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically generated VHDL (Sun Mar 13 17:13:30 2022)
  constant N_SLV_ARP_CONTROL: integer := 0;
  constant N_SLV_ARP_TIMEOUT_LENGTHS: integer := 1;
  constant N_SLV_POSITIONS_ACTIVE: integer := 2;
  constant N_SLV_ARP_MODE_ENTRY: integer := 3;
  constant N_SLAVES: integer := 4;
-- END automatically generated VHDL

    
end ipbus_decode_arp_mode_ctrl_mmap_ipb;

package body ipbus_decode_arp_mode_ctrl_mmap_ipb is

  function ipbus_sel_arp_mode_ctrl_mmap_ipb(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically generated VHDL (Sun Mar 13 17:13:30 2022)
    if    std_match(addr, "-----------------------0----0-0-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_ARP_CONTROL, IPBUS_SEL_WIDTH)); -- arp_control / base 0x00000000 / mask 0x0000010a
    elsif std_match(addr, "-----------------------0----0-1-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_ARP_TIMEOUT_LENGTHS, IPBUS_SEL_WIDTH)); -- arp_timeout_lengths / base 0x00000002 / mask 0x0000010a
    elsif std_match(addr, "-----------------------0----1---") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_POSITIONS_ACTIVE, IPBUS_SEL_WIDTH)); -- positions_active / base 0x00000008 / mask 0x00000108
    elsif std_match(addr, "-----------------------1--------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_ARP_MODE_ENTRY, IPBUS_SEL_WIDTH)); -- arp_mode_entry / base 0x00000100 / mask 0x00000100
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_arp_mode_ctrl_mmap_ipb;

end ipbus_decode_arp_mode_ctrl_mmap_ipb;

