-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_tx_mux_wib is

  constant IPBUS_SEL_WIDTH: positive := 2;
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_tx_mux_wib(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically generated VHDL (Tue Jan 17 20:01:29 2023)
  constant N_SLV_MUX: integer := 0;
  constant N_SLV_UDP: integer := 1;
  constant N_SLAVES: integer := 2;
-- END automatically generated VHDL

    
end ipbus_decode_tx_mux_wib;

package body ipbus_decode_tx_mux_wib is

  function ipbus_sel_tx_mux_wib(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically generated VHDL (Tue Jan 17 20:01:29 2023)
    if    std_match(addr, "-----------------------0--------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_MUX, IPBUS_SEL_WIDTH)); -- mux / base 0x00000000 / mask 0x00000100
    elsif std_match(addr, "-----------------------1--------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_UDP, IPBUS_SEL_WIDTH)); -- udp / base 0x00000100 / mask 0x00000100
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_tx_mux_wib;

end ipbus_decode_tx_mux_wib;

