create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list daq_clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {daq_stream[0][0]} {daq_stream[0][1]} {daq_stream[0][2]} {daq_stream[0][3]} {daq_stream[0][4]} {daq_stream[0][5]} {daq_stream[0][6]} {daq_stream[0][7]} {daq_stream[0][8]} {daq_stream[0][9]} {daq_stream[0][10]} {daq_stream[0][11]} {daq_stream[0][12]} {daq_stream[0][13]} {daq_stream[0][14]} {daq_stream[0][15]} {daq_stream[0][16]} {daq_stream[0][17]} {daq_stream[0][18]} {daq_stream[0][19]} {daq_stream[0][20]} {daq_stream[0][21]} {daq_stream[0][22]} {daq_stream[0][23]} {daq_stream[0][24]} {daq_stream[0][25]} {daq_stream[0][26]} {daq_stream[0][27]} {daq_stream[0][28]} {daq_stream[0][29]} {daq_stream[0][30]} {daq_stream[0][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {daq_stream[1][0]} {daq_stream[1][1]} {daq_stream[1][2]} {daq_stream[1][3]} {daq_stream[1][4]} {daq_stream[1][5]} {daq_stream[1][6]} {daq_stream[1][7]} {daq_stream[1][8]} {daq_stream[1][9]} {daq_stream[1][10]} {daq_stream[1][11]} {daq_stream[1][12]} {daq_stream[1][13]} {daq_stream[1][14]} {daq_stream[1][15]} {daq_stream[1][16]} {daq_stream[1][17]} {daq_stream[1][18]} {daq_stream[1][19]} {daq_stream[1][20]} {daq_stream[1][21]} {daq_stream[1][22]} {daq_stream[1][23]} {daq_stream[1][24]} {daq_stream[1][25]} {daq_stream[1][26]} {daq_stream[1][27]} {daq_stream[1][28]} {daq_stream[1][29]} {daq_stream[1][30]} {daq_stream[1][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {daq_stream_k[0][0]} {daq_stream_k[0][1]} {daq_stream_k[0][2]} {daq_stream_k[0][3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {daq_stream_k[1][0]} {daq_stream_k[1][1]} {daq_stream_k[1][2]} {daq_stream_k[1][3]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets daq_clk_IBUF_BUFG]
